In [36]:
import pandas as pd
import numpy as np

In [2]:
# list current working directory
! ls

LICENSE          __pycache__      experiment.ipynb parse.py
README.md        data             models.py        reviews

In [3]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.kernel_ridge import KernelRidge
from parse import *

In [4]:
data = get_processed_data()

HAS NANS:  host_response_time
HAS NANS:  host_response_rate
HAS NANS:  host_acceptance_rate
HAS NANS:  beds
Removing NaNs from:  host_response_rate
94.95238095238095
Removing NaNs from:  host_acceptance_rate
92.05413804383383
Removing NaNs from:  host_response_time
within an hour
Removing NaNs from:  beds
1.0
Columns are NaN free!!!!!!
{'a few days or more': 0, 'within a few hours': 1, 'within an hour': 2, 'within a day': 3}
{'f': 0, 't': 1}
{'f': 0, 't': 1}
{'Townhouse': 0, 'Yurt': 1, 'Villa': 2, 'Guesthouse': 3, 'House': 4, 'Bed & Breakfast': 5, 'Bungalow': 6, 'Dorm': 7, 'Condominium': 8, 'Entire Floor': 9, 'Other': 10, 'Apartment': 11, 'Chalet': 12, 'Loft': 13, 'Boat': 14, 'Camper/RV': 15, 'Tent': 16, 'Treehouse': 17, 'Cabin': 18}
{'Private room': 0, 'Entire home/apt': 1, 'Shared room': 2}
{'Pull-out Sofa': 0, 'Airbed': 1, 'Real Bed': 2, 'Couch': 3, 'Futon': 4}
{'moderate': 0, 'flexible': 1, 'super_strict_30': 2, 'strict': 3}
      Unnamed: 0        id  host_response_time  host_response_rate  \
0              0  12147973                   2           94.952381
1              1   3075044                   2          100.000000
2              2      6976                   1          100.000000
3              3   1436513                   1          100.000000
4              4   7651065                   2          100.000000
5              5  12386020                   1          100.000000
6              6   5706985                   2           98.000000
7              7   2843445                   1          100.000000
8              8    753446                   2          100.000000
9              9    849408                   2          100.000000
10            10  12023024                   3           83.000000
11            11   1668313                   2          100.000000
12            12   2684840                   1          100.000000
13            13  13547301                   2          100.000000
14            14   5434353                   3           75.000000
15            15    225979                   2          100.000000
16            16   3420384                   1          100.000000
17            17  13512930                   1          100.000000
18            18   7482195                   3          100.000000
19            19   7252607                   3          100.000000
20            20   2583074                   1          100.000000
21            21  13251243                   2          100.000000
22            22    225834                   2          100.000000
23            23   6400432                   3          100.000000
24            24   5498472                   2           94.952381
25            25    894539                   2          100.000000
26            26    879929                   2          100.000000
27            27   9218312                   1          100.000000
28            28    321328                   3           60.000000
29            29   1810172                   2          100.000000
...          ...       ...                 ...                 ...
7321        7321   7745196                   2          100.000000
7322        7322   4645405                   1          100.000000
7323        7323   2755730                   2          100.000000
7324        7324   7949448                   1          100.000000
7325        7325   9288840                   2          100.000000
7326        7326   3312406                   2          100.000000
7327        7327   6621924                   1           80.000000
7328        7328   5673552                   2          100.000000
7329        7329    609701                   2          100.000000
7330        7330  10118341                   2          100.000000
7331        7331   2614387                   2          100.000000
7332        7332   7735100                   0           25.000000
7333        7333   5482204                   2           94.952381
7334        7334   4524575                   1          100.000000
7335        7335   8562314                   2           94.952381
7336        7336   9698202                   1           97.000000
7337        7337   7178490                   1          100.000000
7338        7338   8054902                   2          100.000000
7339        7339   5458027                   2          100.000000
7340        7340   4940491                   3          100.000000
7341        7341   1844791                   1          100.000000
7342        7342   6120046                   3          100.000000
7343        7343    262764                   2          100.000000
7344        7344   8578490                   1          100.000000
7345        7345   3383329                   2          100.000000
7346        7346   8101950                   1           99.000000
7347        7347   8902327                   2          100.000000
7348        7348  10267360                   2           94.952381
7349        7349   9604740                   2          100.000000
7350        7350  10208623                   3          100.000000

      host_acceptance_rate  host_is_superhost  host_total_listings_count  \
0                92.054138                  0                          1
1               100.000000                  0                          1
2                88.000000                  1                          1
3                50.000000                  0                          1
4               100.000000                  1                          1
5                95.000000                  1                          2
6                96.000000                  0                          5
7               100.000000                  1                          2
8               100.000000                  1                          1
9               100.000000                  1                          2
10              100.000000                  0                          1
11               89.000000                  1                          2
12              100.000000                  0                          2
13               97.000000                  0                          1
14              100.000000                  0                          1
15               79.000000                  0                          2
16              100.000000                  0                          1
17              100.000000                  0                          2
18              100.000000                  1                          3
19              100.000000                  1                          3
20               94.000000                  1                          3
21              100.000000                  0                          1
22               79.000000                  0                          2
23               63.000000                  0                          1
24               92.054138                  0                          1
25               92.000000                  1                          2
26              100.000000                  0                          1
27              100.000000                  1                          1
28              100.000000                  0                          1
29               89.000000                  1                          2
...                    ...                ...                        ...
7321            100.000000                  0                          1
7322            100.000000                  0                          2
7323            100.000000                  1                          1
7324            100.000000                  0                          1
7325             92.054138                  0                          1
7326            100.000000                  1                          1
7327            100.000000                  0                          1
7328            100.000000                  1                          1
7329            100.000000                  1                          1
7330            100.000000                  0                          1
7331            100.000000                  0                          2
7332            100.000000                  0                          1
7333             92.054138                  0                          1
7334            100.000000                  1                          1
7335             92.054138                  0                          1
7336            100.000000                  0                          9
7337            100.000000                  1                          1
7338            100.000000                  0                          1
7339            100.000000                  1                          2
7340            100.000000                  0                          1
7341            100.000000                  0                          2
7342            100.000000                  0                          1
7343            100.000000                  0                          1
7344            100.000000                  0                          1
7345            100.000000                  1                          3
7346            100.000000                  0                        354
7347            100.000000                  0                          1
7348             92.054138                  0                          1
7349             92.054138                  0                          1
7350             92.054138                  0                          1

      host_identity_verified   latitude   longitude         ...           \
0                          0  42.282619  -71.133068         ...
1                          1  42.286241  -71.134374         ...
2                          1  42.292438  -71.135765         ...
3                          0  42.281106  -71.121021         ...
4                          1  42.284512  -71.136258         ...
5                          1  42.291690  -71.131893         ...
6                          1  42.281390  -71.131190         ...
7                          1  42.281946  -71.141022         ...
8                          1  42.285878  -71.124910         ...
9                          1  42.288820  -71.139510         ...
10                         0  42.286448  -71.139325         ...
11                         1  42.281942  -71.133372         ...
12                         0  42.291723  -71.131556         ...
13                         1  42.287641  -71.129883         ...
14                         1  42.286265  -71.137065         ...
15                         0  42.281452  -71.129250         ...
16                         0  42.274408  -71.125294         ...
17                         0  42.291815  -71.131588         ...
18                         1  42.282225  -71.115189         ...
19                         1  42.282802  -71.115145         ...
20                         1  42.279648  -71.136059         ...
21                         1  42.294035  -71.132237         ...
22                         0  42.280528  -71.130843         ...
23                         1  42.278383  -71.128780         ...
24                         0  42.276831  -71.129560         ...
25                         1  42.290904  -71.130238         ...
26                         0  42.291520  -71.131858         ...
27                         1  42.289071  -71.128233         ...
28                         1  42.292238  -71.134497         ...
29                         1  42.282086  -71.133349         ...
...                      ...        ...         ...         ...
7321                       1  47.656739 -122.344865         ...
7322                       1  47.661171 -122.349923         ...
7323                       1  47.649271 -122.347817         ...
7324                       1  47.659149 -122.363466         ...
7325                       0  47.663040 -122.348499         ...
7326                       1  47.660056 -122.357683         ...
7327                       1  47.654199 -122.359987         ...
7328                       1  47.650124 -122.343283         ...
7329                       1  47.656508 -122.360571         ...
7330                       1  47.658976 -122.354915         ...
7331                       1  47.655381 -122.343205         ...
7332                       1  47.652902 -122.352110         ...
7333                       0  47.663613 -122.349519         ...
7334                       1  47.657078 -122.358795         ...
7335                       0  47.650765 -122.347787         ...
7336                       1  47.661131 -122.349238         ...
7337                       1  47.660856 -122.352401         ...
7338                       1  47.653158 -122.356285         ...
7339                       1  47.656057 -122.354514         ...
7340                       0  47.654304 -122.342720         ...
7341                       1  47.662036 -122.350485         ...
7342                       1  47.648689 -122.343915         ...
7343                       1  47.654205 -122.352604         ...
7344                       1  47.657898 -122.346692         ...
7345                       1  47.654516 -122.358124         ...
7346                       1  47.664295 -122.359170         ...
7347                       1  47.649552 -122.318309         ...
7348                       0  47.508453 -122.240607         ...
7349                       1  47.632335 -122.275530         ...
7350                       1  47.641186 -122.342085         ...

      Cable TV  Essentials  Wheelchair Accessible  Fire Extinguisher  \
0            0           1                      0                  1
1            0           1                      0                  1
2            1           1                      0                  0
3            0           1                      0                  1
4            0           1                      0                  0
5            1           0                      0                  0
6            0           1                      0                  1
7            0           1                      0                  1
8            0           0                      0                  0
9            1           1                      0                  1
10           0           1                      0                  0
11           1           0                      0                  0
12           1           1                      0                  1
13           0           1                      0                  1
14           0           1                      0                  1
15           0           1                      0                  1
16           1           0                      0                  1
17           0           1                      0                  1
18           1           1                      0                  0
19           0           1                      0                  0
20           0           1                      0                  0
21           0           1                      0                  1
22           0           1                      0                  1
23           0           0                      0                  0
24           1           1                      0                  1
25           1           1                      0                  1
26           0           0                      0                  0
27           0           1                      0                  1
28           0           0                      0                  0
29           1           1                      0                  0
...        ...         ...                    ...                ...
7321         0           1                      0                  1
7322         0           1                      0                  1
7323         0           1                      0                  1
7324         1           1                      0                  0
7325         1           1                      0                  1
7326         1           1                      0                  0
7327         0           1                      0                  0
7328         1           1                      0                  1
7329         1           1                      0                  1
7330         0           1                      0                  1
7331         0           1                      0                  1
7332         0           1                      0                  0
7333         1           1                      0                  1
7334         1           1                      0                  1
7335         0           1                      0                  1
7336         0           1                      0                  1
7337         0           1                      0                  1
7338         0           1                      1                  1
7339         0           1                      0                  1
7340         1           1                      0                  0
7341         1           1                      0                  1
7342         0           1                      1                  1
7343         1           1                      0                  1
7344         1           1                      0                  0
7345         0           1                      0                  1
7346         1           1                      1                  1
7347         1           1                      0                  1
7348         1           1                      0                  1
7349         0           1                      0                  0
7350         1           1                      0                  0

      Hair Dryer  Buzzer/Wireless Intercom  Laptop Friendly Workspace  \
0              0                         0                          1
1              1                         0                          0
2              0                         0                          0
3              1                         0                          1
4              1                         0                          0
5              0                         0                          0
6              0                         0                          0
7              1                         0                          1
8              1                         0                          0
9              1                         0                          1
10             1                         0                          0
11             0                         0                          0
12             1                         0                          1
13             1                         0                          1
14             0                         0                          0
15             0                         0                          0
16             0                         0                          0
17             1                         0                          1
18             0                         0                          0
19             0                         0                          0
20             0                         1                          0
21             1                         0                          1
22             0                         0                          1
23             0                         0                          0
24             0                         0                          0
25             1                         0                          1
26             0                         0                          0
27             0                         0                          1
28             0                         0                          0

In [17]:
data.head()

,Unnamed: 0,id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,latitude,longitude,...,Cable TV,Essentials,Wheelchair Accessible,Fire Extinguisher,Hair Dryer,Buzzer/Wireless Intercom,Laptop Friendly Workspace,Lock on Bedroom Door,Family/Kid Friendly,verifications_count
0,0,12147973,2,94.952381,92.054138,0,1,0,42.282619,-71.133068,...,0,1,0,1,0,0,1,0,1,4
1,1,3075044,2,100.000000,100.000000,0,1,1,42.286241,-71.134374,...,0,1,0,1,1,0,0,1,1,7
2,2,6976,1,100.000000,88.000000,1,1,1,42.292438,-71.135765,...,1,1,0,0,0,0,0,1,0,4
3,3,1436513,1,100.000000,50.000000,0,1,0,42.281106,-71.121021,...,0,1,0,1,1,0,1,0,0,3
4,4,7651065,2,100.000000,100.000000,1,1,1,42.284512,-71.136258,...,0,1,0,0,1,0,0,0,0,4

In [12]:
y = data['price']
X = data.drop(['price', 'Unnamed: 0', 'id'], axis=1) # drop 'Unnamed: 0' and 'id'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train.head()

,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_identity_verified,latitude,longitude,property_type,room_type,...,Cable TV,Essentials,Wheelchair Accessible,Fire Extinguisher,Hair Dryer,Buzzer/Wireless Intercom,Laptop Friendly Workspace,Lock on Bedroom Door,Family/Kid Friendly,verifications_count
2202,1,96.0,68.0,0,313,1,42.344175,-71.098479,11,1,...,1,0,0,0,0,0,0,0,1,6
2900,1,79.0,100.0,0,18,1,42.318034,-71.054511,11,0,...,0,0,0,0,0,0,0,0,0,4
5426,2,100.0,100.0,0,1,1,47.560736,-122.382494,0,0,...,0,1,1,0,0,0,0,0,1,6
5663,2,100.0,100.0,0,2,1,47.588753,-122.311076,4,0,...,0,1,0,1,0,0,0,0,1,4
2860,1,100.0,45.0,1,1,1,42.308293,-71.076642,4,0,...,0,1,0,1,0,0,0,0,1,4

In [57]:
# regularization bench mark
clf = RandomForestRegressor(n_estimators=300, criterion='mae', max_features='sqrt', max_depth=None, n_jobs=-1)
clf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=None,
           max_features='sqrt', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [58]:
print('training accuracy:', clf.score(X_train, y_train))
print('test accuracy:    ', clf.score(X_test, y_test))

training accuracy: 0.9153468532227844
test accuracy:     0.6147413640264247

In [73]:
# increase max_features a little bit (increase too much will reduce test accuracy)
clf_trial = RandomForestRegressor(n_estimators=300, criterion='mae', 
                                  max_features=14, max_depth=None, 
                                  n_jobs=-1, oob_score=True)
clf_trial.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=None,
           max_features=14, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=300, n_jobs=-1, oob_score=True, random_state=None,
           verbose=0, warm_start=False)

In [74]:
print('training accuracy:', clf_trial.score(X_train, y_train))
print('test accuracy:    ', clf_trial.score(X_test, y_test))

training accuracy: 0.9094587232171256
test accuracy:     0.6272205000371243